//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Частный_детектив
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sms
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Sender { get; set; }
        public int DetectiveId { get; set; }
        public int ClientId { get; set; }
    }
}
