//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Частный_детектив
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string TextZayavki { get; set; }
        public string Status { get; set; }
        public int DetectiveId { get; set; }
    
        public virtual Detective Detective { get; set; }
    }
}
